/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppChatPatientIdRouteImport } from './routes/app.chat.$patientId'
import { Route as AppAdminNutritionistsRouteImport } from './routes/app.admin.nutritionists'
import { Route as AppAdminIntegrationsRouteImport } from './routes/app.admin.integrations'
import { Route as AppAdminAdministratorsRouteImport } from './routes/app.admin.administrators'
import { Route as ApiDifyUploadRouteImport } from './routes/api/dify.upload'
import { Route as ApiDifyChatRouteImport } from './routes/api/dify.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppChatPatientIdRoute = AppChatPatientIdRouteImport.update({
  id: '/chat/$patientId',
  path: '/chat/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNutritionistsRoute = AppAdminNutritionistsRouteImport.update({
  id: '/admin/nutritionists',
  path: '/admin/nutritionists',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIntegrationsRoute = AppAdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAdministratorsRoute = AppAdminAdministratorsRouteImport.update({
  id: '/admin/administrators',
  path: '/admin/administrators',
  getParentRoute: () => AppRoute,
} as any)
const ApiDifyUploadRoute = ApiDifyUploadRouteImport.update({
  id: '/api/dify/upload',
  path: '/api/dify/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyChatRoute = ApiDifyChatRouteImport.update({
  id: '/api/dify/chat',
  path: '/api/dify/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/': typeof AppIndexRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/patients': typeof AppPatientsRoute
  '/app': typeof AppIndexRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/': typeof AppIndexRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/patients'
    | '/app/'
    | '/api/dify/chat'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/chat/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/patients'
    | '/app'
    | '/api/dify/chat'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/chat/$patientId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/patients'
    | '/app/'
    | '/api/dify/chat'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/chat/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDifyChatRoute: typeof ApiDifyChatRoute
  ApiDifyUploadRoute: typeof ApiDifyUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$patientId': {
      id: '/app/chat/$patientId'
      path: '/chat/$patientId'
      fullPath: '/app/chat/$patientId'
      preLoaderRoute: typeof AppChatPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/nutritionists': {
      id: '/app/admin/nutritionists'
      path: '/admin/nutritionists'
      fullPath: '/app/admin/nutritionists'
      preLoaderRoute: typeof AppAdminNutritionistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/integrations': {
      id: '/app/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/app/admin/integrations'
      preLoaderRoute: typeof AppAdminIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/administrators': {
      id: '/app/admin/administrators'
      path: '/admin/administrators'
      fullPath: '/app/admin/administrators'
      preLoaderRoute: typeof AppAdminAdministratorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/dify/upload': {
      id: '/api/dify/upload'
      path: '/api/dify/upload'
      fullPath: '/api/dify/upload'
      preLoaderRoute: typeof ApiDifyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/chat': {
      id: '/api/dify/chat'
      path: '/api/dify/chat'
      fullPath: '/api/dify/chat'
      preLoaderRoute: typeof ApiDifyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPatientsRoute: typeof AppPatientsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAdministratorsRoute: typeof AppAdminAdministratorsRoute
  AppAdminIntegrationsRoute: typeof AppAdminIntegrationsRoute
  AppAdminNutritionistsRoute: typeof AppAdminNutritionistsRoute
  AppChatPatientIdRoute: typeof AppChatPatientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPatientsRoute: AppPatientsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAdministratorsRoute: AppAdminAdministratorsRoute,
  AppAdminIntegrationsRoute: AppAdminIntegrationsRoute,
  AppAdminNutritionistsRoute: AppAdminNutritionistsRoute,
  AppChatPatientIdRoute: AppChatPatientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDifyChatRoute: ApiDifyChatRoute,
  ApiDifyUploadRoute: ApiDifyUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
