/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPoliticasRouteImport } from './routes/app.politicas'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppEvolutionPatientIdRouteImport } from './routes/app.evolution.$patientId'
import { Route as AppChatPatientIdRouteImport } from './routes/app.chat.$patientId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminRankingRouteImport } from './routes/app.admin.ranking'
import { Route as AppAdminPlaygroundRouteImport } from './routes/app.admin.playground'
import { Route as AppAdminNutritionistsRouteImport } from './routes/app.admin.nutritionists'
import { Route as AppAdminIntegrationsRouteImport } from './routes/app.admin.integrations'
import { Route as AppAdminFeedbacksRouteImport } from './routes/app.admin.feedbacks'
import { Route as AppAdminAdministratorsRouteImport } from './routes/app.admin.administrators'
import { Route as ApiDifyUploadRouteImport } from './routes/api/dify.upload'
import { Route as ApiDifyTestRouteImport } from './routes/api/dify.test'
import { Route as ApiDifyResetConversationsRouteImport } from './routes/api/dify.reset-conversations'
import { Route as ApiDifyChatRouteImport } from './routes/api/dify.chat'
import { Route as ApiAuditStructuredRouteImport } from './routes/api/audit.structured'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliticasRoute = AppPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionPatientIdRoute = AppEvolutionPatientIdRouteImport.update({
  id: '/evolution/$patientId',
  path: '/evolution/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatPatientIdRoute = AppChatPatientIdRouteImport.update({
  id: '/chat/$patientId',
  path: '/chat/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRankingRoute = AppAdminRankingRouteImport.update({
  id: '/admin/ranking',
  path: '/admin/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlaygroundRoute = AppAdminPlaygroundRouteImport.update({
  id: '/admin/playground',
  path: '/admin/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNutritionistsRoute = AppAdminNutritionistsRouteImport.update({
  id: '/admin/nutritionists',
  path: '/admin/nutritionists',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIntegrationsRoute = AppAdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFeedbacksRoute = AppAdminFeedbacksRouteImport.update({
  id: '/admin/feedbacks',
  path: '/admin/feedbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAdministratorsRoute = AppAdminAdministratorsRouteImport.update({
  id: '/admin/administrators',
  path: '/admin/administrators',
  getParentRoute: () => AppRoute,
} as any)
const ApiDifyUploadRoute = ApiDifyUploadRouteImport.update({
  id: '/api/dify/upload',
  path: '/api/dify/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyTestRoute = ApiDifyTestRouteImport.update({
  id: '/api/dify/test',
  path: '/api/dify/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyResetConversationsRoute =
  ApiDifyResetConversationsRouteImport.update({
    id: '/api/dify/reset-conversations',
    path: '/api/dify/reset-conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDifyChatRoute = ApiDifyChatRouteImport.update({
  id: '/api/dify/chat',
  path: '/api/dify/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditStructuredRoute = ApiAuditStructuredRouteImport.update({
  id: '/api/audit/structured',
  path: '/api/audit/structured',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/unauthorized'
    | '/app/dashboard'
    | '/app/patients'
    | '/app/politicas'
    | '/app/settings'
    | '/app/'
    | '/api/audit/structured'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/feedbacks'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/evolution/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/app/dashboard'
    | '/app/patients'
    | '/app/politicas'
    | '/app/settings'
    | '/app'
    | '/api/audit/structured'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/feedbacks'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/evolution/$patientId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/unauthorized'
    | '/app/dashboard'
    | '/app/patients'
    | '/app/politicas'
    | '/app/settings'
    | '/app/'
    | '/api/audit/structured'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/app/admin/administrators'
    | '/app/admin/feedbacks'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/evolution/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuditStructuredRoute: typeof ApiAuditStructuredRoute
  ApiDifyChatRoute: typeof ApiDifyChatRoute
  ApiDifyResetConversationsRoute: typeof ApiDifyResetConversationsRoute
  ApiDifyTestRoute: typeof ApiDifyTestRoute
  ApiDifyUploadRoute: typeof ApiDifyUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/politicas': {
      id: '/app/politicas'
      path: '/politicas'
      fullPath: '/app/politicas'
      preLoaderRoute: typeof AppPoliticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolution/$patientId': {
      id: '/app/evolution/$patientId'
      path: '/evolution/$patientId'
      fullPath: '/app/evolution/$patientId'
      preLoaderRoute: typeof AppEvolutionPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$patientId': {
      id: '/app/chat/$patientId'
      path: '/chat/$patientId'
      fullPath: '/app/chat/$patientId'
      preLoaderRoute: typeof AppChatPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ranking': {
      id: '/app/admin/ranking'
      path: '/admin/ranking'
      fullPath: '/app/admin/ranking'
      preLoaderRoute: typeof AppAdminRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/playground': {
      id: '/app/admin/playground'
      path: '/admin/playground'
      fullPath: '/app/admin/playground'
      preLoaderRoute: typeof AppAdminPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/nutritionists': {
      id: '/app/admin/nutritionists'
      path: '/admin/nutritionists'
      fullPath: '/app/admin/nutritionists'
      preLoaderRoute: typeof AppAdminNutritionistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/integrations': {
      id: '/app/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/app/admin/integrations'
      preLoaderRoute: typeof AppAdminIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/feedbacks': {
      id: '/app/admin/feedbacks'
      path: '/admin/feedbacks'
      fullPath: '/app/admin/feedbacks'
      preLoaderRoute: typeof AppAdminFeedbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/administrators': {
      id: '/app/admin/administrators'
      path: '/admin/administrators'
      fullPath: '/app/admin/administrators'
      preLoaderRoute: typeof AppAdminAdministratorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/dify/upload': {
      id: '/api/dify/upload'
      path: '/api/dify/upload'
      fullPath: '/api/dify/upload'
      preLoaderRoute: typeof ApiDifyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/test': {
      id: '/api/dify/test'
      path: '/api/dify/test'
      fullPath: '/api/dify/test'
      preLoaderRoute: typeof ApiDifyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/reset-conversations': {
      id: '/api/dify/reset-conversations'
      path: '/api/dify/reset-conversations'
      fullPath: '/api/dify/reset-conversations'
      preLoaderRoute: typeof ApiDifyResetConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/chat': {
      id: '/api/dify/chat'
      path: '/api/dify/chat'
      fullPath: '/api/dify/chat'
      preLoaderRoute: typeof ApiDifyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/structured': {
      id: '/api/audit/structured'
      path: '/api/audit/structured'
      fullPath: '/api/audit/structured'
      preLoaderRoute: typeof ApiAuditStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPoliticasRoute: typeof AppPoliticasRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAdministratorsRoute: typeof AppAdminAdministratorsRoute
  AppAdminFeedbacksRoute: typeof AppAdminFeedbacksRoute
  AppAdminIntegrationsRoute: typeof AppAdminIntegrationsRoute
  AppAdminNutritionistsRoute: typeof AppAdminNutritionistsRoute
  AppAdminPlaygroundRoute: typeof AppAdminPlaygroundRoute
  AppAdminRankingRoute: typeof AppAdminRankingRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppChatPatientIdRoute: typeof AppChatPatientIdRoute
  AppEvolutionPatientIdRoute: typeof AppEvolutionPatientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPoliticasRoute: AppPoliticasRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAdministratorsRoute: AppAdminAdministratorsRoute,
  AppAdminFeedbacksRoute: AppAdminFeedbacksRoute,
  AppAdminIntegrationsRoute: AppAdminIntegrationsRoute,
  AppAdminNutritionistsRoute: AppAdminNutritionistsRoute,
  AppAdminPlaygroundRoute: AppAdminPlaygroundRoute,
  AppAdminRankingRoute: AppAdminRankingRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppChatPatientIdRoute: AppChatPatientIdRoute,
  AppEvolutionPatientIdRoute: AppEvolutionPatientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuditStructuredRoute: ApiAuditStructuredRoute,
  ApiDifyChatRoute: ApiDifyChatRoute,
  ApiDifyResetConversationsRoute: ApiDifyResetConversationsRoute,
  ApiDifyTestRoute: ApiDifyTestRoute,
  ApiDifyUploadRoute: ApiDifyUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
