/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPoliticasRouteImport } from './routes/app.politicas'
import { Route as AppPlanosRouteImport } from './routes/app.planos'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppFaleComLummaRouteImport } from './routes/app.fale-com-lumma'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatsRouteImport } from './routes/app.chats'
import { Route as AppPlanosHistoricoRouteImport } from './routes/app.planos.historico'
import { Route as AppGeneralChatIdRouteImport } from './routes/app.general.$chatId'
import { Route as AppEvolutionPatientIdRouteImport } from './routes/app.evolution.$patientId'
import { Route as AppCheckoutSucessoRouteImport } from './routes/app.checkout.sucesso'
import { Route as AppChatPatientIdRouteImport } from './routes/app.chat.$patientId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminRankingRouteImport } from './routes/app.admin.ranking'
import { Route as AppAdminPlaygroundRouteImport } from './routes/app.admin.playground'
import { Route as AppAdminPlansRouteImport } from './routes/app.admin.plans'
import { Route as AppAdminNutritionistsRouteImport } from './routes/app.admin.nutritionists'
import { Route as AppAdminIntegrationsRouteImport } from './routes/app.admin.integrations'
import { Route as AppAdminImportNutriRouteImport } from './routes/app.admin.import-nutri'
import { Route as AppAdminFeedbacksRouteImport } from './routes/app.admin.feedbacks'
import { Route as AppAdminEmailsRouteImport } from './routes/app.admin.emails'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppAdminCreditsAuditRouteImport } from './routes/app.admin.credits-audit'
import { Route as AppAdminAgentCostsRouteImport } from './routes/app.admin.agent-costs'
import { Route as AppAdminAdministratorsRouteImport } from './routes/app.admin.administrators'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicKiwifyWebhookRouteImport } from './routes/api/public/kiwify-webhook'
import { Route as ApiDifyUploadRouteImport } from './routes/api/dify.upload'
import { Route as ApiDifyTestRouteImport } from './routes/api/dify.test'
import { Route as ApiDifyResetConversationsRouteImport } from './routes/api/dify.reset-conversations'
import { Route as ApiDifyChatRouteImport } from './routes/api/dify.chat'
import { Route as ApiDifyAgentTestRouteImport } from './routes/api/dify.agent-test'
import { Route as ApiAuditStructuredRouteImport } from './routes/api/audit.structured'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliticasRoute = AppPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppFaleComLummaRoute = AppFaleComLummaRouteImport.update({
  id: '/fale-com-lumma',
  path: '/fale-com-lumma',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosHistoricoRoute = AppPlanosHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppPlanosRoute,
} as any)
const AppGeneralChatIdRoute = AppGeneralChatIdRouteImport.update({
  id: '/general/$chatId',
  path: '/general/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionPatientIdRoute = AppEvolutionPatientIdRouteImport.update({
  id: '/evolution/$patientId',
  path: '/evolution/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutSucessoRoute = AppCheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => AppRoute,
} as any)
const AppChatPatientIdRoute = AppChatPatientIdRouteImport.update({
  id: '/chat/$patientId',
  path: '/chat/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRankingRoute = AppAdminRankingRouteImport.update({
  id: '/admin/ranking',
  path: '/admin/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlaygroundRoute = AppAdminPlaygroundRouteImport.update({
  id: '/admin/playground',
  path: '/admin/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNutritionistsRoute = AppAdminNutritionistsRouteImport.update({
  id: '/admin/nutritionists',
  path: '/admin/nutritionists',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIntegrationsRoute = AppAdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminImportNutriRoute = AppAdminImportNutriRouteImport.update({
  id: '/admin/import-nutri',
  path: '/admin/import-nutri',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFeedbacksRoute = AppAdminFeedbacksRouteImport.update({
  id: '/admin/feedbacks',
  path: '/admin/feedbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailsRoute = AppAdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCreditsAuditRoute = AppAdminCreditsAuditRouteImport.update({
  id: '/admin/credits-audit',
  path: '/admin/credits-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAgentCostsRoute = AppAdminAgentCostsRouteImport.update({
  id: '/admin/agent-costs',
  path: '/admin/agent-costs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAdministratorsRoute = AppAdminAdministratorsRouteImport.update({
  id: '/admin/administrators',
  path: '/admin/administrators',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKiwifyWebhookRoute = ApiPublicKiwifyWebhookRouteImport.update({
  id: '/api/public/kiwify-webhook',
  path: '/api/public/kiwify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyUploadRoute = ApiDifyUploadRouteImport.update({
  id: '/api/dify/upload',
  path: '/api/dify/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyTestRoute = ApiDifyTestRouteImport.update({
  id: '/api/dify/test',
  path: '/api/dify/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyResetConversationsRoute =
  ApiDifyResetConversationsRouteImport.update({
    id: '/api/dify/reset-conversations',
    path: '/api/dify/reset-conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDifyChatRoute = ApiDifyChatRouteImport.update({
  id: '/api/dify/chat',
  path: '/api/dify/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDifyAgentTestRoute = ApiDifyAgentTestRouteImport.update({
  id: '/api/dify/agent-test',
  path: '/api/dify/agent-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditStructuredRoute = ApiAuditStructuredRouteImport.update({
  id: '/api/audit/structured',
  path: '/api/audit/structured',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fale-com-lumma': typeof AppFaleComLummaRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/planos': typeof AppPlanosRouteWithChildren
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/agent-test': typeof ApiDifyAgentTestRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/agent-costs': typeof AppAdminAgentCostsRoute
  '/app/admin/credits-audit': typeof AppAdminCreditsAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/import-nutri': typeof AppAdminImportNutriRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/checkout/sucesso': typeof AppCheckoutSucessoRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
  '/app/general/$chatId': typeof AppGeneralChatIdRoute
  '/app/planos/historico': typeof AppPlanosHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fale-com-lumma': typeof AppFaleComLummaRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/planos': typeof AppPlanosRouteWithChildren
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/agent-test': typeof ApiDifyAgentTestRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/agent-costs': typeof AppAdminAgentCostsRoute
  '/app/admin/credits-audit': typeof AppAdminCreditsAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/import-nutri': typeof AppAdminImportNutriRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/checkout/sucesso': typeof AppCheckoutSucessoRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
  '/app/general/$chatId': typeof AppGeneralChatIdRoute
  '/app/planos/historico': typeof AppPlanosHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fale-com-lumma': typeof AppFaleComLummaRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/planos': typeof AppPlanosRouteWithChildren
  '/app/politicas': typeof AppPoliticasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/audit/structured': typeof ApiAuditStructuredRoute
  '/api/dify/agent-test': typeof ApiDifyAgentTestRoute
  '/api/dify/chat': typeof ApiDifyChatRoute
  '/api/dify/reset-conversations': typeof ApiDifyResetConversationsRoute
  '/api/dify/test': typeof ApiDifyTestRoute
  '/api/dify/upload': typeof ApiDifyUploadRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/admin/administrators': typeof AppAdminAdministratorsRoute
  '/app/admin/agent-costs': typeof AppAdminAgentCostsRoute
  '/app/admin/credits-audit': typeof AppAdminCreditsAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/feedbacks': typeof AppAdminFeedbacksRoute
  '/app/admin/import-nutri': typeof AppAdminImportNutriRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/nutritionists': typeof AppAdminNutritionistsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/playground': typeof AppAdminPlaygroundRoute
  '/app/admin/ranking': typeof AppAdminRankingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$patientId': typeof AppChatPatientIdRoute
  '/app/checkout/sucesso': typeof AppCheckoutSucessoRoute
  '/app/evolution/$patientId': typeof AppEvolutionPatientIdRoute
  '/app/general/$chatId': typeof AppGeneralChatIdRoute
  '/app/planos/historico': typeof AppPlanosHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/unauthorized'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/fale-com-lumma'
    | '/app/patients'
    | '/app/planos'
    | '/app/politicas'
    | '/app/settings'
    | '/app/'
    | '/api/audit/structured'
    | '/api/dify/agent-test'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/api/public/kiwify-webhook'
    | '/api/public/stripe-webhook'
    | '/app/admin/administrators'
    | '/app/admin/agent-costs'
    | '/app/admin/credits-audit'
    | '/app/admin/dashboard'
    | '/app/admin/emails'
    | '/app/admin/feedbacks'
    | '/app/admin/import-nutri'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/plans'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/checkout/sucesso'
    | '/app/evolution/$patientId'
    | '/app/general/$chatId'
    | '/app/planos/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/unauthorized'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/fale-com-lumma'
    | '/app/patients'
    | '/app/planos'
    | '/app/politicas'
    | '/app/settings'
    | '/app'
    | '/api/audit/structured'
    | '/api/dify/agent-test'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/api/public/kiwify-webhook'
    | '/api/public/stripe-webhook'
    | '/app/admin/administrators'
    | '/app/admin/agent-costs'
    | '/app/admin/credits-audit'
    | '/app/admin/dashboard'
    | '/app/admin/emails'
    | '/app/admin/feedbacks'
    | '/app/admin/import-nutri'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/plans'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/checkout/sucesso'
    | '/app/evolution/$patientId'
    | '/app/general/$chatId'
    | '/app/planos/historico'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/unauthorized'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/fale-com-lumma'
    | '/app/patients'
    | '/app/planos'
    | '/app/politicas'
    | '/app/settings'
    | '/app/'
    | '/api/audit/structured'
    | '/api/dify/agent-test'
    | '/api/dify/chat'
    | '/api/dify/reset-conversations'
    | '/api/dify/test'
    | '/api/dify/upload'
    | '/api/public/kiwify-webhook'
    | '/api/public/stripe-webhook'
    | '/app/admin/administrators'
    | '/app/admin/agent-costs'
    | '/app/admin/credits-audit'
    | '/app/admin/dashboard'
    | '/app/admin/emails'
    | '/app/admin/feedbacks'
    | '/app/admin/import-nutri'
    | '/app/admin/integrations'
    | '/app/admin/nutritionists'
    | '/app/admin/plans'
    | '/app/admin/playground'
    | '/app/admin/ranking'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/chat/$patientId'
    | '/app/checkout/sucesso'
    | '/app/evolution/$patientId'
    | '/app/general/$chatId'
    | '/app/planos/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManutencaoRoute: typeof ManutencaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuditStructuredRoute: typeof ApiAuditStructuredRoute
  ApiDifyAgentTestRoute: typeof ApiDifyAgentTestRoute
  ApiDifyChatRoute: typeof ApiDifyChatRoute
  ApiDifyResetConversationsRoute: typeof ApiDifyResetConversationsRoute
  ApiDifyTestRoute: typeof ApiDifyTestRoute
  ApiDifyUploadRoute: typeof ApiDifyUploadRoute
  ApiPublicKiwifyWebhookRoute: typeof ApiPublicKiwifyWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/politicas': {
      id: '/app/politicas'
      path: '/politicas'
      fullPath: '/app/politicas'
      preLoaderRoute: typeof AppPoliticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos': {
      id: '/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fale-com-lumma': {
      id: '/app/fale-com-lumma'
      path: '/fale-com-lumma'
      fullPath: '/app/fale-com-lumma'
      preLoaderRoute: typeof AppFaleComLummaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats': {
      id: '/app/chats'
      path: '/chats'
      fullPath: '/app/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos/historico': {
      id: '/app/planos/historico'
      path: '/historico'
      fullPath: '/app/planos/historico'
      preLoaderRoute: typeof AppPlanosHistoricoRouteImport
      parentRoute: typeof AppPlanosRoute
    }
    '/app/general/$chatId': {
      id: '/app/general/$chatId'
      path: '/general/$chatId'
      fullPath: '/app/general/$chatId'
      preLoaderRoute: typeof AppGeneralChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolution/$patientId': {
      id: '/app/evolution/$patientId'
      path: '/evolution/$patientId'
      fullPath: '/app/evolution/$patientId'
      preLoaderRoute: typeof AppEvolutionPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout/sucesso': {
      id: '/app/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/app/checkout/sucesso'
      preLoaderRoute: typeof AppCheckoutSucessoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$patientId': {
      id: '/app/chat/$patientId'
      path: '/chat/$patientId'
      fullPath: '/app/chat/$patientId'
      preLoaderRoute: typeof AppChatPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ranking': {
      id: '/app/admin/ranking'
      path: '/admin/ranking'
      fullPath: '/app/admin/ranking'
      preLoaderRoute: typeof AppAdminRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/playground': {
      id: '/app/admin/playground'
      path: '/admin/playground'
      fullPath: '/app/admin/playground'
      preLoaderRoute: typeof AppAdminPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/plans': {
      id: '/app/admin/plans'
      path: '/admin/plans'
      fullPath: '/app/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/nutritionists': {
      id: '/app/admin/nutritionists'
      path: '/admin/nutritionists'
      fullPath: '/app/admin/nutritionists'
      preLoaderRoute: typeof AppAdminNutritionistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/integrations': {
      id: '/app/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/app/admin/integrations'
      preLoaderRoute: typeof AppAdminIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/import-nutri': {
      id: '/app/admin/import-nutri'
      path: '/admin/import-nutri'
      fullPath: '/app/admin/import-nutri'
      preLoaderRoute: typeof AppAdminImportNutriRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/feedbacks': {
      id: '/app/admin/feedbacks'
      path: '/admin/feedbacks'
      fullPath: '/app/admin/feedbacks'
      preLoaderRoute: typeof AppAdminFeedbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/emails': {
      id: '/app/admin/emails'
      path: '/admin/emails'
      fullPath: '/app/admin/emails'
      preLoaderRoute: typeof AppAdminEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/credits-audit': {
      id: '/app/admin/credits-audit'
      path: '/admin/credits-audit'
      fullPath: '/app/admin/credits-audit'
      preLoaderRoute: typeof AppAdminCreditsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/agent-costs': {
      id: '/app/admin/agent-costs'
      path: '/admin/agent-costs'
      fullPath: '/app/admin/agent-costs'
      preLoaderRoute: typeof AppAdminAgentCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/administrators': {
      id: '/app/admin/administrators'
      path: '/admin/administrators'
      fullPath: '/app/admin/administrators'
      preLoaderRoute: typeof AppAdminAdministratorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiwify-webhook': {
      id: '/api/public/kiwify-webhook'
      path: '/api/public/kiwify-webhook'
      fullPath: '/api/public/kiwify-webhook'
      preLoaderRoute: typeof ApiPublicKiwifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/upload': {
      id: '/api/dify/upload'
      path: '/api/dify/upload'
      fullPath: '/api/dify/upload'
      preLoaderRoute: typeof ApiDifyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/test': {
      id: '/api/dify/test'
      path: '/api/dify/test'
      fullPath: '/api/dify/test'
      preLoaderRoute: typeof ApiDifyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/reset-conversations': {
      id: '/api/dify/reset-conversations'
      path: '/api/dify/reset-conversations'
      fullPath: '/api/dify/reset-conversations'
      preLoaderRoute: typeof ApiDifyResetConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/chat': {
      id: '/api/dify/chat'
      path: '/api/dify/chat'
      fullPath: '/api/dify/chat'
      preLoaderRoute: typeof ApiDifyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dify/agent-test': {
      id: '/api/dify/agent-test'
      path: '/api/dify/agent-test'
      fullPath: '/api/dify/agent-test'
      preLoaderRoute: typeof ApiDifyAgentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/structured': {
      id: '/api/audit/structured'
      path: '/api/audit/structured'
      fullPath: '/api/audit/structured'
      preLoaderRoute: typeof ApiAuditStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPlanosRouteChildren {
  AppPlanosHistoricoRoute: typeof AppPlanosHistoricoRoute
}

const AppPlanosRouteChildren: AppPlanosRouteChildren = {
  AppPlanosHistoricoRoute: AppPlanosHistoricoRoute,
}

const AppPlanosRouteWithChildren = AppPlanosRoute._addFileChildren(
  AppPlanosRouteChildren,
)

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFaleComLummaRoute: typeof AppFaleComLummaRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPlanosRoute: typeof AppPlanosRouteWithChildren
  AppPoliticasRoute: typeof AppPoliticasRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAdministratorsRoute: typeof AppAdminAdministratorsRoute
  AppAdminAgentCostsRoute: typeof AppAdminAgentCostsRoute
  AppAdminCreditsAuditRoute: typeof AppAdminCreditsAuditRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminEmailsRoute: typeof AppAdminEmailsRoute
  AppAdminFeedbacksRoute: typeof AppAdminFeedbacksRoute
  AppAdminImportNutriRoute: typeof AppAdminImportNutriRoute
  AppAdminIntegrationsRoute: typeof AppAdminIntegrationsRoute
  AppAdminNutritionistsRoute: typeof AppAdminNutritionistsRoute
  AppAdminPlansRoute: typeof AppAdminPlansRoute
  AppAdminPlaygroundRoute: typeof AppAdminPlaygroundRoute
  AppAdminRankingRoute: typeof AppAdminRankingRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppChatPatientIdRoute: typeof AppChatPatientIdRoute
  AppCheckoutSucessoRoute: typeof AppCheckoutSucessoRoute
  AppEvolutionPatientIdRoute: typeof AppEvolutionPatientIdRoute
  AppGeneralChatIdRoute: typeof AppGeneralChatIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFaleComLummaRoute: AppFaleComLummaRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPlanosRoute: AppPlanosRouteWithChildren,
  AppPoliticasRoute: AppPoliticasRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAdministratorsRoute: AppAdminAdministratorsRoute,
  AppAdminAgentCostsRoute: AppAdminAgentCostsRoute,
  AppAdminCreditsAuditRoute: AppAdminCreditsAuditRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminEmailsRoute: AppAdminEmailsRoute,
  AppAdminFeedbacksRoute: AppAdminFeedbacksRoute,
  AppAdminImportNutriRoute: AppAdminImportNutriRoute,
  AppAdminIntegrationsRoute: AppAdminIntegrationsRoute,
  AppAdminNutritionistsRoute: AppAdminNutritionistsRoute,
  AppAdminPlansRoute: AppAdminPlansRoute,
  AppAdminPlaygroundRoute: AppAdminPlaygroundRoute,
  AppAdminRankingRoute: AppAdminRankingRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppChatPatientIdRoute: AppChatPatientIdRoute,
  AppCheckoutSucessoRoute: AppCheckoutSucessoRoute,
  AppEvolutionPatientIdRoute: AppEvolutionPatientIdRoute,
  AppGeneralChatIdRoute: AppGeneralChatIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ManutencaoRoute: ManutencaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuditStructuredRoute: ApiAuditStructuredRoute,
  ApiDifyAgentTestRoute: ApiDifyAgentTestRoute,
  ApiDifyChatRoute: ApiDifyChatRoute,
  ApiDifyResetConversationsRoute: ApiDifyResetConversationsRoute,
  ApiDifyTestRoute: ApiDifyTestRoute,
  ApiDifyUploadRoute: ApiDifyUploadRoute,
  ApiPublicKiwifyWebhookRoute: ApiPublicKiwifyWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
